# Generated by Django 3.2.4 on 2021-07-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameProduct', models.CharField(max_length=1000)),
                ('Size', models.CharField(max_length=1000)),
                ('Color', models.CharField(max_length=1000)),
                ('Attribute', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=1000)),
                ('Height', models.CharField(max_length=1000)),
                ('Width', models.CharField(max_length=1000)),
                ('Number', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Size', models.CharField(max_length=1000)),
                ('Color', models.CharField(max_length=1000)),
                ('Attribute', models.CharField(max_length=1000)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
