# Generated by Django 3.2.4 on 2021-07-16 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_conversationmodel_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Number',
            field=models.IntegerField(default=100),
        ),
    ]
