# Generated by Django 3.2.4 on 2021-07-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0003_productmodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmodel',
            name='Ass',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='Waist',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='Attribute',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='Color',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='Height',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='Name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='Number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='Size',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='Width',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
