version: "3.9"
   
services:
    db:
        image: postgres:latest
        container_name: postgresql1
        volumes:
            - tutorial-volume:/app/postgresql/data
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=conversations
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - djangonetwork
    backend:    
        build: ./backend
        container_name: django_backend1
        command: >
            sh -c "python manage.py migrate --run-syncdb && python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./backend:/app/backend
        environment:
            - DB_HOST=db
            - DB_USER=postgres
            - DB_PASS=postgres
            - DB_NAME=conversations
        ports:
            - "8000:8000"
        networks:
            - djangonetwork
        depends_on:
            - db
    frontend:
        build: ./frontend
        container_name: react_frontend
        environment:
            - DOCKER_CLIENT_TIMEOUT=120
            - COMPOSE_HTTP_TIMEOUT=120
        volumes:
            - ./frontend:/app/frontend
            - /app/frontend/node_modules
        ports:
            - "3000:3000"
        command: ["npm", "start"]
volumes:
    tutorial-volume:
networks:
    djangonetwork:
        driver: bridge
    
    
