version: '3'

services:
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/app/db/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: ./api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app/frontend
      - node-modules:/app/frontend/node_modules
    ports:
      - "3000:3000"
  pytorch:
    build: ./pytorch
    volumes:
      - ./pytorch:/app/pytorch
    command: python pytorch.py
volumes:
  node-modules:
